name: Release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches:
      - main

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7

      - name: Generate and push version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          tag_prefix: ""

      - name: Download build artifacts
        id: download
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        id: publish
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "artifacts/resizer-x64/resizer_x64.exe,artifacts/resizer-x86/resizer_x86.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
